//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIONSYS.Plugin.POS {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class POSSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static POSSettings defaultInstance = ((POSSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new POSSettings())));
        
        public static POSSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TS-00000001")]
        public string TransferNumber {
            get {
                return ((string)(this["TransferNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IN-00000001")]
        public string InvoiceNumber {
            get {
                return ((string)(this["InvoiceNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RT-00000001")]
        public string ReturnNumber {
            get {
                return ((string)(this["ReturnNumber"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CD-00000001")]
        public string CreditNumber {
            get {
                return ((string)(this["CreditNumber"]));
            }
            set {
                this["CreditNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PC-00000001")]
        public string PurchaseNumber {
            get {
                return ((string)(this["PurchaseNumber"]));
            }
            set {
                this["PurchaseNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExpenseNumber {
            get {
                return ((string)(this["ExpenseNumber"]));
            }
            set {
                this["ExpenseNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RMA-0000001")]
        public string RMANumber {
            get {
                return ((string)(this["RMANumber"]));
            }
            set {
                this["RMANumber"] = value;
            }
        }
    }
}
