//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADIONSYS.Plugin.POS {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class POSSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static POSSettings defaultInstance = ((POSSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new POSSettings())));
        
        public static POSSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TS-00000001")]
        public string TransferNumber {
            get {
                return ((string)(this["TransferNumber"]));
            }
            set {
                this["TransferNumber"] = value;
            }
        }
    }
}
